<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;

    public static function boot()
    {
        parent::boot();  // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $pegawai = Pegawai::orderByDesc('id')->first();
            $id = 1;
            $kode_acehtimur = '5104';
            $model->nk = $kode_acehtimur . str_pad($model->unit_kerja->satuan_kerja_id, 2, '0', STR_PAD_LEFT) . str_pad($pegawai->id+$id, 4, '0', STR_PAD_LEFT);
        });
    }

    protected $fillable = [
        'nik',
        'npwp',
        'nuptk',
        'gelar_depan',
        'gelar_belakang',
        'tanggal_lulus',
        'nomor_ijazah',
        'jurusan',
        'institusi',
        'pendidikan_id',
        'unit_kerja_id',
        'kecamatan_id',
        'alamat',
        'ho_hp',
        'email',
        'tmt',
        'honorarium',
        'jenis_tenaga_kontrak_id',
        'jabatan_id',
        'foto',
        'ktp',
        'kk',
        'ijazah',
        'str',
        'user_id',
        'status'
    ];

    public function pendidikan()
    {
        return $this->belongsTo(Pendidikan::class);
    }

    public function unit_kerja()
    {
        return $this->belongsTo(UnitKerja::class);
    }

    public function kecamatan()
    {
        return $this->belongsTo(Kecamatan::class);
    }

    public function usulan()
    {
        return $this->belongsToMany(Usulan::class);
    }

    public function operator()
    {
        return $this->belongsTo(User::class, 'by');
    }

    public function jenis_kontrak()
    {
        return $this->belongsTo(JenisTenagaKontrak::class, 'jenis_tenaga_kontrak_id');
    }
}
